language: julia
os:
  - linux
julia:
  - 1.0
  - nightly
notifications:
  email: false
script:
  - julia -e 'using Pkg; Pkg.build(); Pkg.test("CoverageBase"; coverage=true)'
  - julia -e 'using Pkg; Pkg.add(PackageSpec(name="Coverage", rev="master")); using Coverage; Codecov.submit(Codecov.process_folder())'
